
version: '2'

services:
  # nginx:
  #   image: nginx
  #   depends_on:
  #     - website
  #     # - website
  #   ports:
  #     - 80:80
  website:
    build: .
    image: ba40431/travel-project:latest
    restart: always
    env_file:
      - ./.env
    environment:
      - PORT=3000